# Generated by Django 3.2 on 2021-06-10 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutor',
            name='slots',
            field=models.CharField(default='', max_length=255),
        ),
    ]
