# Generated by Django 3.2 on 2021-06-16 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_tutor_is_favourite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutor',
            name='fees',
            field=models.IntegerField(),
        ),
    ]
