# Generated by Django 3.2 on 2021-06-17 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_tutor_fees'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wednesday',
            fields=[
                ('wednesday', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='accounts.tutor')),
                ('slot_9_10', models.BooleanField(default=False)),
                ('slot_10_11', models.BooleanField(default=False)),
                ('slot_11_12', models.BooleanField(default=False)),
                ('slot_12_13', models.BooleanField(default=False)),
                ('slot_13_14', models.BooleanField(default=False)),
                ('slot_14_15', models.BooleanField(default=False)),
                ('slot_15_16', models.BooleanField(default=False)),
                ('slot_16_17', models.BooleanField(default=False)),
                ('slot_17_18', models.BooleanField(default=False)),
                ('slot_18_19', models.BooleanField(default=False)),
                ('slot_19_20', models.BooleanField(default=False)),
            ],
        ),
    ]
