# Generated by Django 3.2 on 2021-06-18 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_friday_saturday_sunday_thursday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monday',
            name='slot_10_11',
            field=models.CharField(default='0', max_length=255),
        ),
        migrations.AlterField(
            model_name='monday',
            name='slot_11_12',
            field=models.CharField(default='0', max_length=255),
        ),
        migrations.AlterField(
            model_name='monday',
            name='slot_12_13',
            field=models.CharField(default='0', max_length=255),
        ),
        migrations.AlterField(
            model_name='monday',
            name='slot_13_14',
            field=models.CharField(default='0', max_length=255),
        ),
        migrations.AlterField(
            model_name='monday',
            name='slot_14_15',
            field=models.CharField(default='0', max_length=255),
        ),
        migrations.AlterField(
            model_name='monday',
            name='slot_15_16',
            field=models.CharField(default='0', max_length=255),
        ),
        migrations.AlterField(
            model_name='monday',
            name='slot_16_17',
            field=models.CharField(default='0', max_length=255),
        ),
        migrations.AlterField(
            model_name='monday',
            name='slot_17_18',
            field=models.CharField(default='0', max_length=255),
        ),
        migrations.AlterField(
            model_name='monday',
            name='slot_18_19',
            field=models.CharField(default='0', max_length=255),
        ),
        migrations.AlterField(
            model_name='monday',
            name='slot_19_20',
            field=models.CharField(default='0', max_length=255),
        ),
        migrations.AlterField(
            model_name='monday',
            name='slot_9_10',
            field=models.CharField(default='0', max_length=255),
        ),
    ]
