# Generated by Django 3.2 on 2021-06-18 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20210618_1825'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutor',
            name='experience',
            field=models.IntegerField(default=0),
        ),
    ]
