# Generated by Django 3.2 on 2021-06-26 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_tutor_mapurl'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stud_name', models.CharField(default='', max_length=255)),
                ('tutor_name', models.CharField(default='', max_length=255)),
                ('fee', models.IntegerField(default=0)),
                ('date', models.CharField(default='', max_length=255)),
                ('time', models.CharField(default='', max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='tutor',
            name='fees',
            field=models.IntegerField(default=0),
        ),
    ]
