# Generated by Django 3.2 on 2021-06-26 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20210626_2122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friday',
            name='slot_10_11',
            field=models.CharField(default='0', max_length=255),
        ),
        migrations.AlterField(
            model_name='friday',
            name='slot_11_12',
            field=models.CharField(default='0', max_length=255),
        ),
        migrations.AlterField(
            model_name='friday',
            name='slot_12_13',
            field=models.CharField(default='0', max_length=255),
        ),
        migrations.AlterField(
            model_name='friday',
            name='slot_13_14',
            field=models.CharField(default='0', max_length=255),
        ),
        migrations.AlterField(
            model_name='friday',
            name='slot_14_15',
            field=models.CharField(default='0', max_length=255),
        ),
        migrations.AlterField(
            model_name='friday',
            name='slot_15_16',
            field=models.CharField(default='0', max_length=255),
        ),
        migrations.AlterField(
            model_name='friday',
            name='slot_16_17',
            field=models.CharField(default='0', max_length=255),
        ),
        migrations.AlterField(
            model_name='friday',
            name='slot_17_18',
            field=models.CharField(default='0', max_length=255),
        ),
        migrations.AlterField(
            model_name='friday',
            name='slot_18_19',
            field=models.CharField(default='0', max_length=255),
        ),
        migrations.AlterField(
            model_name='friday',
            name='slot_19_20',
            field=models.CharField(default='0', max_length=255),
        ),
        migrations.AlterField(
            model_name='friday',
            name='slot_9_10',
            field=models.CharField(default='0', max_length=255),
        ),
        migrations.AlterField(
            model_name='saturday',
            name='slot_10_11',
            field=models.CharField(default='0', max_length=255),
        ),
        migrations.AlterField(
            model_name='saturday',
            name='slot_11_12',
            field=models.CharField(default='0', max_length=255),
        ),
        migrations.AlterField(
            model_name='saturday',
            name='slot_12_13',
            field=models.CharField(default='0', max_length=255),
        ),
        migrations.AlterField(
            model_name='saturday',
            name='slot_13_14',
            field=models.CharField(default='0', max_length=255),
        ),
        migrations.AlterField(
            model_name='saturday',
            name='slot_14_15',
            field=models.CharField(default='0', max_length=255),
        ),
        migrations.AlterField(
            model_name='saturday',
            name='slot_15_16',
            field=models.CharField(default='0', max_length=255),
        ),
        migrations.AlterField(
            model_name='saturday',
            name='slot_16_17',
            field=models.CharField(default='0', max_length=255),
        ),
        migrations.AlterField(
            model_name='saturday',
            name='slot_17_18',
            field=models.CharField(default='0', max_length=255),
        ),
        migrations.AlterField(
            model_name='saturday',
            name='slot_18_19',
            field=models.CharField(default='0', max_length=255),
        ),
        migrations.AlterField(
            model_name='saturday',
            name='slot_19_20',
            field=models.CharField(default='0', max_length=255),
        ),
        migrations.AlterField(
            model_name='saturday',
            name='slot_9_10',
            field=models.CharField(default='0', max_length=255),
        ),
        migrations.AlterField(
            model_name='sunday',
            name='slot_10_11',
            field=models.CharField(default='0', max_length=255),
        ),
        migrations.AlterField(
            model_name='sunday',
            name='slot_11_12',
            field=models.CharField(default='0', max_length=255),
        ),
        migrations.AlterField(
            model_name='sunday',
            name='slot_12_13',
            field=models.CharField(default='0', max_length=255),
        ),
        migrations.AlterField(
            model_name='sunday',
            name='slot_13_14',
            field=models.CharField(default='0', max_length=255),
        ),
        migrations.AlterField(
            model_name='sunday',
            name='slot_14_15',
            field=models.CharField(default='0', max_length=255),
        ),
        migrations.AlterField(
            model_name='sunday',
            name='slot_15_16',
            field=models.CharField(default='0', max_length=255),
        ),
        migrations.AlterField(
            model_name='sunday',
            name='slot_16_17',
            field=models.CharField(default='0', max_length=255),
        ),
        migrations.AlterField(
            model_name='sunday',
            name='slot_17_18',
            field=models.CharField(default='0', max_length=255),
        ),
        migrations.AlterField(
            model_name='sunday',
            name='slot_18_19',
            field=models.CharField(default='0', max_length=255),
        ),
        migrations.AlterField(
            model_name='sunday',
            name='slot_19_20',
            field=models.CharField(default='0', max_length=255),
        ),
        migrations.AlterField(
            model_name='sunday',
            name='slot_9_10',
            field=models.CharField(default='0', max_length=255),
        ),
        migrations.AlterField(
            model_name='thursday',
            name='slot_10_11',
            field=models.CharField(default='0', max_length=255),
        ),
        migrations.AlterField(
            model_name='thursday',
            name='slot_11_12',
            field=models.CharField(default='0', max_length=255),
        ),
        migrations.AlterField(
            model_name='thursday',
            name='slot_12_13',
            field=models.CharField(default='0', max_length=255),
        ),
        migrations.AlterField(
            model_name='thursday',
            name='slot_13_14',
            field=models.CharField(default='0', max_length=255),
        ),
        migrations.AlterField(
            model_name='thursday',
            name='slot_14_15',
            field=models.CharField(default='0', max_length=255),
        ),
        migrations.AlterField(
            model_name='thursday',
            name='slot_15_16',
            field=models.CharField(default='0', max_length=255),
        ),
        migrations.AlterField(
            model_name='thursday',
            name='slot_16_17',
            field=models.CharField(default='0', max_length=255),
        ),
        migrations.AlterField(
            model_name='thursday',
            name='slot_17_18',
            field=models.CharField(default='0', max_length=255),
        ),
        migrations.AlterField(
            model_name='thursday',
            name='slot_18_19',
            field=models.CharField(default='0', max_length=255),
        ),
        migrations.AlterField(
            model_name='thursday',
            name='slot_19_20',
            field=models.CharField(default='0', max_length=255),
        ),
        migrations.AlterField(
            model_name='thursday',
            name='slot_9_10',
            field=models.CharField(default='0', max_length=255),
        ),
        migrations.AlterField(
            model_name='tuesday',
            name='slot_10_11',
            field=models.CharField(default='0', max_length=255),
        ),
        migrations.AlterField(
            model_name='tuesday',
            name='slot_11_12',
            field=models.CharField(default='0', max_length=255),
        ),
        migrations.AlterField(
            model_name='tuesday',
            name='slot_12_13',
            field=models.CharField(default='0', max_length=255),
        ),
        migrations.AlterField(
            model_name='tuesday',
            name='slot_13_14',
            field=models.CharField(default='0', max_length=255),
        ),
        migrations.AlterField(
            model_name='tuesday',
            name='slot_14_15',
            field=models.CharField(default='0', max_length=255),
        ),
        migrations.AlterField(
            model_name='tuesday',
            name='slot_15_16',
            field=models.CharField(default='0', max_length=255),
        ),
        migrations.AlterField(
            model_name='tuesday',
            name='slot_16_17',
            field=models.CharField(default='0', max_length=255),
        ),
        migrations.AlterField(
            model_name='tuesday',
            name='slot_17_18',
            field=models.CharField(default='0', max_length=255),
        ),
        migrations.AlterField(
            model_name='tuesday',
            name='slot_18_19',
            field=models.CharField(default='0', max_length=255),
        ),
        migrations.AlterField(
            model_name='tuesday',
            name='slot_19_20',
            field=models.CharField(default='0', max_length=255),
        ),
        migrations.AlterField(
            model_name='tuesday',
            name='slot_9_10',
            field=models.CharField(default='0', max_length=255),
        ),
        migrations.AlterField(
            model_name='wednesday',
            name='slot_10_11',
            field=models.CharField(default='0', max_length=255),
        ),
        migrations.AlterField(
            model_name='wednesday',
            name='slot_11_12',
            field=models.CharField(default='0', max_length=255),
        ),
        migrations.AlterField(
            model_name='wednesday',
            name='slot_12_13',
            field=models.CharField(default='0', max_length=255),
        ),
        migrations.AlterField(
            model_name='wednesday',
            name='slot_13_14',
            field=models.CharField(default='0', max_length=255),
        ),
        migrations.AlterField(
            model_name='wednesday',
            name='slot_14_15',
            field=models.CharField(default='0', max_length=255),
        ),
        migrations.AlterField(
            model_name='wednesday',
            name='slot_15_16',
            field=models.CharField(default='0', max_length=255),
        ),
        migrations.AlterField(
            model_name='wednesday',
            name='slot_16_17',
            field=models.CharField(default='0', max_length=255),
        ),
        migrations.AlterField(
            model_name='wednesday',
            name='slot_17_18',
            field=models.CharField(default='0', max_length=255),
        ),
        migrations.AlterField(
            model_name='wednesday',
            name='slot_18_19',
            field=models.CharField(default='0', max_length=255),
        ),
        migrations.AlterField(
            model_name='wednesday',
            name='slot_19_20',
            field=models.CharField(default='0', max_length=255),
        ),
        migrations.AlterField(
            model_name='wednesday',
            name='slot_9_10',
            field=models.CharField(default='0', max_length=255),
        ),
    ]
