# Generated by Django 3.2 on 2021-06-27 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_alter_orders_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutor',
            name='video',
            field=models.FileField(default='', upload_to='videos/'),
        ),
    ]
