# Generated by Django 3.2 on 2021-06-27 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_tutor_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='stud_email',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='orders',
            name='time1',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='orders',
            name='tutor_email',
            field=models.CharField(default='', max_length=255),
        ),
    ]
