# Generated by Django 3.2 on 2021-06-27 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_auto_20210627_2341'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='stud_phn',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='orders',
            name='tutor_phn',
            field=models.CharField(default='', max_length=255),
        ),
    ]
