# Generated by Django 3.2 on 2021-06-30 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_orders_day'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myuser',
            old_name='is_student',
            new_name='is_favourite',
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='is_tutor',
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='locality',
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='phn_num',
        ),
        migrations.AddField(
            model_name='myuser',
            name='phonenum',
            field=models.CharField(default='', max_length=10),
        ),
    ]
