# Generated by Django 3.2 on 2021-07-01 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_auto_20210630_1727'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutor',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
