# Generated by Django 3.2 on 2021-07-03 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_tutor_is_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutor',
            name='meeting',
            field=models.URLField(default=''),
        ),
    ]
